# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for Twelve-Tone Music Analyzer."""

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('src/', 'src'),
    ],
    hiddenimports=[
        # PyQt5
        'PyQt5',
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'PyQt5.QtWidgets',
        # music21
        'music21',
        'music21.converter',
        'music21.converter.subConverters',
        'music21.converter.subConverters.ConverterMusicXML',
        'music21.converter.subConverters.ConverterMEI',
        'music21.converter.subConverters.ConverterMIDI',
        'music21.serial',
        'music21.chord',
        'music21.note',
        'music21.pitch',
        'music21.stream',
        'music21.meter',
        'music21.key',
        'music21.graph',
        'music21.graph.plot',
        'music21.interval',
        'music21.clef',
        'music21.tempo',
        'music21.duration',
        'music21.layout',
        # matplotlib
        'matplotlib',
        'matplotlib.backends.backend_qt5agg',
        'matplotlib.backends.backend_agg',
        'matplotlib.figure',
        # numpy
        'numpy',
        'numpy.core._methods',
        'numpy.linalg._linalg',
        # librosa
        'librosa',
        'librosa.core',
        'librosa.display',
        'librosa.feature',
        # sklearn
        'sklearn',
        'sklearn.preprocessing',
        'sklearn.cluster',
        # networkx
        'networkx',
        'networkx.drawing',
        'networkx.drawing.nx_agraph',
        # requests
        'requests',
        # project modules
        'src',
        'src.core',
        'src.core.file_manager',
        'src.core.score_analyzer',
        'src.core.twelve_tone',
        'src.core.chord_analyzer',
        'src.core.audio_analyzer',
        'src.core.inclusion_lattice',
        'src.core.set_relations',
        'src.ui',
        'src.ui.main_window',
        'src.ui.theme',
        'src.ui.tabs',
        'src.ui.tabs.overview_tab',
        'src.ui.tabs.visualization_tab',
        'src.ui.tabs.twelve_tone_tab',
        'src.ui.tabs.chord_tab',
        'src.ui.tabs.audio_tab',
        'src.ui.tabs.lattice_tab',
        'src.ui.tabs.annotated_score_tab',
        'src.ui.tabs.forte_name_tab',
        'src.ui.tabs.set_relations_tab',
        'src.ui.widgets',
        'src.ui.widgets.plot_canvas',
        'src.ui.widgets.matrix_widget',
        'src.ui.widgets.score_view',
        'src.ui.widgets.score_opener',
        'src.ui.dialogs',
        'src.ui.dialogs.settings_dialog',
        'src.ui.dialogs.musescore_prompt',
        'src.utils',
        'src.utils.config',
        'src.utils.i18n',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='TwelveToneAnalyzer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
